* FOR INFORMATION ABOUT POINT GO TO 
'http://web.utk.edu/sas/OnlineTutor/1.2/en/60476/m14/m14_14.htm'
GO THROUGH THE NEXT TWO PAGES FOR IMP INFORMATION;

DATA Test1;
    OBSNUM=2;
    SET TEXT.TEST POINT=OBSNUM;
    OUTPUT;
    STOP;
RUN;
PROC PRINT DATA=Test1 NOOBS;
RUN;
